export const userActionTypes = {
  LOGIN_REQUEST: " LOGIN_REQUEST",
  LOGIN_SUCCESS: " LOGIN_SUCCESS",
  LOGIN_FAIL: " LOGIN_FAIL",

  REGISTER_REQUEST: " REGISTER_REQUEST",
  REGISTER_SUCCESS: " REGISTER_SUCCESS",
  REGISTER_FAIL: " REGISTER_FAIL",

  LOAD_USER_REQUEST: " LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: " LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: " LOAD_USER_FAIL",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: " LOGOUT_FAIL",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_RESET: "UPDATE_PROFILE_RESET",
  UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",

  UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_RESET: "UPDATE_PASSWORD_RESET",
  UPDATE_PASSWORD_FAIL: "UPDATE_PASSWORD_FAILPASSWORD",
};
